name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CGO_ENABLED: 0

jobs:
  test:
    name: gh-action-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Test
        run: go test ./... -short
